version: '2'
services:
    autosama-app:
        image: autosama
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://autosama-mysql:3306/autosama?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    autosama-mysql:
        extends:
            file: mysql.yml
            service: autosama-mysql
